name:                adventar-bot
version:             0.1.0.0
homepage:            https://github.com/matsubara0507/adventar-bot#readme
license:             MIT
author:              MATSUBARA Nobutada
copyright:           2017 MATSUBARA Nobutada
category:            Web
extra-source-files:
- README.md

ghc-options:
  - -Wall

dependencies:
  - aeson
  - aeson-pretty
  - base >= 4.7 && < 5
  - bytestring
  - mtl
  - scalpel-core
  - slack-api
  - text
  - unordered-containers
  - webdriver

executables:
  adventar-bot:
    source-dirs:      src
    main:             Main.hs
