resolver: lts-9.12
packages:
  - .
extra-deps:
  - slack-api-0.12
flags: {}
extra-package-dbs: []

docker:
  repo: "fpco/stack-build"

image:
  container:
    name: "matsubara0507/adventar-bot"
    base: "matsubara0507/ubuntu-tcp"
    add:
      scripts: /usr/local/bin
