version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
            name: login aws ecr
            command: |
                login="$(aws ecr get-login)"
                ${login}
      - run:
            name: docker-compose up
            command: |
                 docker-compose -f ./docker-compose.yml up -d

general:
  branches:
    only:
      - dump
