version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker/compose
    steps:
      - checkout
      - run:
           name: Exec Bot
           command: |
            set -x
            docker-compose up -d
general:
  branches:
    only:
      - dump
