version: 2
jobs:
  build:
    machine: true
    steps:
      - add-ssh-keys:
          fingerprints:
            - "54:02:33:28:1b:1f:fd:93:44:fd:52:93:22:e3:f5:ad"
      - checkout
      - run:
          name: Git config
          command: |
             git config --global user.email "example@example.com"
             git config --global user.name "Bot"
      - run:
          name: Build Docker Image
          command: docker-compose build
      - run:
          name: docker-compose up
          command: |
            docker-compose -f ./docker-compose.yml run bot
      - run:
          name: Push update json
          command: |
            git status
            git add .
            git commit -m "[skip ci] Update entry.json"
            git push origin dump

workflows:
  version: 2
  normal_workflow:
    jobs:
      - build:
          filters:
            branches:
              only: dump
  nightly_workflow:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only: dump
    jobs:
      - build
